server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: andrei
    url: jdbc:postgresql://postgres:5432/fraud
    password: andrei

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

